version: "3.9"
services:
  gateway:
    container_name: gateway
    image: spring-cloud-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    volumes:
      - "./responses:/opt/app/responses"
  order-api:
    container_name: order-api
    image: order-api:latest
    build:
      context: ./backend-order-api
    ports:
      - "8081:8080"
  echo-api:
    container_name: echo-api
    image: echo-api:latest
    build:
      context: ./backend-echo-api
    ports:
      - "8082:8080"
